dist: trusty
language: python

cache: pip # Cache pip for faster builds

python:
  - "2.7"
  - "3.5"

matrix:
  fast_finish: true

addons:
  apt:
    packages:
      # Packages we need
      - libopenblas-base
      - libopenblas-dev
      - liblapack-dev
      - gfortran

# commands to be run before installation
before_install:
  - pip install --upgrade pip # Upgrade pip, so it can use wheel

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r pymc-requirements.txt
  - pip install -r test-requirements.txt

# command to run tests
script:
  - echo $TRAVIS_PYTHON_VERSION
  - ./run_tests.sh --verbose

# command to run after tests
after_success:
  - coveralls
